<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>GameNet.Agent</RootNamespace>
    <AssemblyName>GameNet.Agent</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <ProjectReference Include="..\Shared\GameNet.Shared.csproj" />
  </ItemGroup>
</Project>
